name: Build App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        arch: [x64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout

      - name: Setup Node.js
        uses: actions/setup-node
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app
        run: |
          npx electron-builder --${{ matrix.os == 'windows-latest' && 'win' || matrix.os == 'macos-latest' && 'mac' || 'linux'}} --${{ matrix.arch }}

      - name: Upload build artifacts
        uses: actions/upload-artifact
        with:
          name: "${{ matrix.os }}-${{ matrix.arch }}"
          path: dist/