name: Modpack Maker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-2022
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Build Windows
        run: npx electron-builder --win --${{ matrix.arch }}

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-build-${{ matrix.arch }}
          path: dist/*.exe

  build-mac:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Build macOS
        run: npx electron-builder --mac
      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-build
          path: dist/*.dmg
